### PR TITLE
Replace Netty 3 with plain old HttpURLConnection

### PR DESCRIPTION
**Pull request by cb372**
Currently the client uses Dispatch, which wraps AsyncHttpClient, which by default uses Netty 3 as its `AsyncHttpProvider`. This is bad for us, because Netty caches DNS resolutions indefinitely, meaning that any DNS magic we do in Route 53 is ignored.

This PR switches AsyncHttpClient's `AsyncHttpProvider` from Netty to JDK, which respects DNS TTLs correctly.

There is a potential performance impact. I have a feeling it will be negligable, but it might be worth benchmarking to check.

Other ideas to try:
* Switch to Netty 4 (will have to wait for the next release of AsyncHttpClient before we can do this; no idea whether it will help)
* Work out how to configure Netty to stop caching DNS (I don't think this is possible)

@mchv @LATaylor-guardian

### CODE REVIEW

**Comment by cb372** [comment]
By the way, the `-Dsun.net.inetaddr.ttl=0` JVM param is not needed. It was a red herring!

**Comment by philmcmahon** [comment]
Code looks good to me, probably best  if Luke or Mariot review this as well.

**Comment by mchv** [comment]
:+1:  this looks good to me and could be useful in the future.

**Comment by cb372** [comment]
Also of interest: we could replace dispatch with OkHttp. It does connection pooling, but it makes it easy to configure how long connections are reused. It also has useful documentation explaining exactly when DNS resolution will happen.

http://square.github.io/okhttp/javadoc/com/squareup/okhttp/ConnectionPool.html
https://github.com/square/okhttp/wiki/Connections

**Comment by cb372** [comment]
Superceded by #65

**Pull request closed without merging**
