### PR TITLE
Bump content-api-models to 8.14.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**

### CODE REVIEW

**Comment by oilnam** [comment]
@LATaylor-guardian can we wait until I add the new fields for Crier?

**Comment by LATaylor-guardian** [comment]
@oilnam If you update the events.thrift file in content-api-models now, create a PR, and then release it, I'll hold off on this PR and then update it to 8.14.

**Comment by oilnam** [comment]
👍

**Comment by cb372** [comment]
Abort abort abort! This cannot be released until we've updated the models in Concierge and deployed that change.

**Comment by LATaylor-guardian** [comment]
It's fine. I haven't released :)

**Comment by LATaylor-guardian** [comment]
@cb372 Concierge updated. Now releasing new version of client.

**Pull request merged**
