### PR TITLE
Add additional fields to thrift model.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**
- Add 'durationMinutes' and 'durationSeconds' field to AssetFields.
- Add 'legallySensitive' field to ContentFields.

### CODE REVIEW

**Comment by cb372** [comment]
:+1: assuming you've placated @philwills about not making the sorta-kinda-mandatory fields `required`

**Comment by LATaylor-guardian** [comment]
I have.

**Comment by philwills** [comment]
I'm a sad panda, but sad with the present, rather than the backwards compatible future.

**Comment by LATaylor-guardian** [comment]
:panda_face:

**Pull request merged**
