### PR TITLE
Add rights

### PR DESCRIPTION
**Pull request by mchv**
* Remove collections from the client
* Add rights in response

cc @JustinPinner

### CODE REVIEW

**Comment by JustinPinner** [comment]
Thanks for the cc Mariot. Was momentarily surprised by the removal of collections, but other than that - looks good.

**Comment by LATaylor-guardian** [comment]
Looks good to me. :+1:

**Comment by cb372** [comment]
:+1: 

Technically this is a breaking change. Should be release a new major version, for the sake of semantic versioning?

**Comment by mchv** [comment]
@cb372 yep just released a `6.0` version to maven

**Pull request merged**
