### PR TITLE
Update version to include Snippet models

### PR DESCRIPTION
**Pull request by annebyrne**
cc @regiskuckaertz

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
Can you update the CHANGELOG also please. It should say what has been added via the version upgrade.

**Comment by tomrf1** [comment]
Remember to update `CHANGELOG.md`

**Comment by LATaylor-guardian** [comment]
Once that's done 👍

**Comment by annebyrne** [comment]
Added changes to CHANGELOG. Will merge when checks pass

**Pull request merged**
