### PR TITLE
Test content-api-model preview version for content-entity

### PR DESCRIPTION
**Pull request by Divs-B**
We are bumping preview version of `content-api-model` that as got `content-entity`'s latest release version to test - https://github.com/guardian/content-entity/actions/runs/8439281276
The other PR for reference: https://github.com/guardian/content-api-models/pull/246

Co-authored: @rtyley 

## How to test

Make a preview release and test in any of client consuming this library, we are going to try it in `apple-news`.

## How can we measure success?

Application should run fine and should not have no conflicts in version or errors in the test.

### CODE REVIEW

**Comment by Divs-B** [comment]
Now we are bumping `content-api-model`'s latest 24.0.0 release version which contains both `content-entity` and `content-atom` latest release.

**Review by rtyley — APPROVED** [review]
Looks good! What's the PR where this was tried in Apple News?

**Comment by Divs-B** [comment]
> Looks good! What's the PR where this was tried in Apple News?

Ah good question, I have checked and tested by running locally on`apple-news` at the time when I was tesing all preview releases, means preview release on this PR work and including other libraries that are required in apple new like `firehose` and `facia-client` too, The `apple-news` was worked as expected so didnt try raising PR. 
I think if its okay, I will do now with these Production releases and will attach here the output from it to confirm.

**Comment by Divs-B** [comment]
This release is verified and tested.
Checked in `facia-client`: https://github.com/guardian/facia-scala-client/pull/312 and at the end tested in one of client using all that is `apple-news`:https://github.com/guardian/apple-news/pull/331

**Pull request merged**
